Add integration tests between the player and the analytics
SRGSSR/pillarbox-android pull request #441
Opened 2024-02-13 14:59 UTC by MGaetan89

# Pull request

## Description

This PR adds new tests to the `Player`, to validate how `ComScoreTracker` and `CommandersActTracker` reacts to player state change.

## Changes made

- Add new tests
- Add constructors dedicated to ease testing
- Make Gradle Wrapper distribution compatible with merge group

## Checklist

- [x] Your branch has been rebased onto the `main` branch.
- [ ] APIs have been properly documented (if relevant).
- [ ] The documentation has been updated (if relevant).
- [x] New unit tests have been written (if relevant).
- [ ] The demo has been updated (if relevant).
- [x] All pull request status checks pass.

2024-02-19 09:59 UTC, StaehliJ requested changes

2024-02-19 09:59 UTC, StaehliJ commented on pillarbox-core-business/src/main/java/ch/srgssr/pillarbox/core/business/tracker/commandersact/CommandersActStreaming.kt
Should not do it there! Do not change validated code from the analytics team!

2024-02-20 14:20 UTC, MGaetan89 commented on pillarbox-core-business/src/main/java/ch/srgssr/pillarbox/core/business/tracker/commandersact/CommandersActStreaming.kt
I've reverted the change in that file, updated the existing tests, and added some new ones.

2024-02-21 12:31 UTC, StaehliJ approved these changes

2024-02-21 12:39 UTC, merged