Improve wording and fix some warnings
SRGSSR/pillarbox-android pull request #678
Opened 2024-08-15 16:02 UTC by MGaetan89

# Pull request

## Description

> Describe enhancements with sufficient details (e.g. implementation considerations, design choices, etc.). For bug reports please mention the issue number that was fixed. If no matching bug report exists you should [open one](https://github.com/SRGSSR/pillarbox-android/issues/new?assignees=&labels=bug%2Ctriage&template=bug_report.yml) first.

## Changes made

> Please list the specific changes made in this pull request.

## Checklist

- [ ] Your branch has been rebased onto the `main` branch.
- [ ] APIs have been properly documented (if relevant).
- [ ] The documentation has been updated (if relevant).
- [ ] New unit tests have been written (if relevant).
- [ ] The demo has been updated (if relevant).
- [ ] All pull request status checks pass.

2024-08-19 13:45 UTC, StaehliJ requested changes

2024-08-19 14:24 UTC, MGaetan89 commented on pillarbox-player/src/main/java/ch/srgssr/pillarbox/player/analytics/extension/EventTime.kt
> +    }
This may be removed now

2024-08-20 09:11 UTC, MGaetan89 commented on pillarbox-player/src/main/java/ch/srgssr/pillarbox/player/analytics/metrics/SessionMetrics.kt
> +            .sumOf { it.bitrate }
I've fixed it in: https://github.com/SRGSSR/pillarbox-android/pull/678/commits/e4ba168c62f86b97108cd6d05b96601f54a46bc0

2024-08-21 07:35 UTC, MGaetan89 commented on pillarbox-player/src/main/java/ch/srgssr/pillarbox/player/analytics/metrics/PlaybackMetrics.kt
> +    val qoeLoadDuration: LoadDuration,
I've reworked that in https://github.com/SRGSSR/pillarbox-android/pull/678/commits/bc85d140ff1dcb0fde5b534334d4f72ca274614d
The `QoSCoordinator` is not in charge of providing QoE and QoS timings, while `PlaybackMetrics` provides overall timings, as before.

2024-08-22 07:24 UTC, MGaetan89 commented on pillarbox-player/src/test/java/ch/srgssr/pillarbox/player/qos/QosCoordinatorTest.kt
> +        val qoeTimings = player.getCurrentQoETimings()
![image](https://github.com/user-attachments/assets/5061b41f-936e-41bf-bb7a-102ab7c55795)

2024-08-28 06:33 UTC, StaehliJ approved these changes

2024-08-28 06:34 UTC, merged